/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Kisuc (props) {
  const { nodes, materials } = useGLTF('/Kisuc-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Curve001.geometry} material={materials.Material} position={[-0.08, -0.16, -0.01]} rotation={[Math.PI / 2, 0, Math.PI ]} />
      <mesh geometry={nodes.Curve003.geometry} material={materials['Material.001']} position={[-0.08, -0.16, -0.01]} rotation={[Math.PI / 2, 0, Math.PI]} />
    </group>
  )
}

useGLTF.preload('/Kisuc-transformed.glb')
